### ISSUE TITLE
hi,😁

### ISSUE THREAD

**Issue by agood-boy** [maxysio/DS-PRJ2-DataStructures#1]
Potential security breach. Google OAuth Key in Url in file [/02-FileSearchRecursion.ipynb](https://github.com/maxysio/DS-PRJ2-DataStructures/tree/master/02-FileSearchRecursion.ipynb)

You should recycle your credenttials immediately and move secrets to environment variables to prevent them being committed to GitHub.

Hope this will be helpful to you！

shout me a coffee ☕️ via [PayPal](https://www.paypal.me/agoodboy)

<a href="https://www.paypal.me/agoodboy">
  <img width="160" height="41" src="https://raw.githubusercontent.com/DWilliames/paddy-sketch-plugin/master/.images/paypal-badge.png" >
</a>

**Comment by maxysio** [comment]
Thanks let me check it out

**Comment by maxysio** [comment]
Removed. Creds updated.
